# Basic Dataset Info

### Key Findings:

* Rows where 'fipscode' is null will be dropped
* 9020 county rows for 'Uninsured' and 'Children in poverty' measures are missing FIPS codes due to a data sourcing issue.
* 561 state/national aggregate rows will be dropped as out of scope.

In [2]:
import pandas as pd

df = pd.read_csv('./data/County_Health_Rankings.csv')

# Display basic information
print(f"Dataset Shape: {df.shape}")
df.head(10)

Dataset Shape: (303864, 14)

,State,County,State code,County code,Year span,Measure name,Measure id,Numerator,Denominator,Raw value,Confidence Interval Lower Bound,Confidence Interval Upper Bound,Data Release Year,fipscode
0,US,United States,0.0,0.0,2003-2005,Violent crime rate,43.0,1.328751e+06,2.748771e+08,483.398066,NaN,NaN,NaN,0.0
1,US,United States,0.0,0.0,2004-2006,Violent crime rate,43.0,1.340929e+06,2.776128e+08,483.021233,NaN,NaN,NaN,0.0
2,US,United States,0.0,0.0,2005-2007,Violent crime rate,43.0,1.355853e+06,2.804077e+08,483.529230,NaN,NaN,2010.0,0.0
3,US,United States,0.0,0.0,2006-2008,Violent crime rate,43.0,1.366928e+06,2.876146e+08,475.263942,NaN,NaN,2011.0,0.0
4,US,United States,0.0,0.0,2007-2009,Violent crime rate,43.0,1.339439e+06,2.925763e+08,457.808585,NaN,NaN,2012.0,0.0
5,US,United States,0.0,0.0,2008-2010,Violent crime rate,43.0,1.295937e+06,2.989479e+08,433.499335,NaN,NaN,2013.0,0.0
6,US,United States,0.0,0.0,2009-2011,Violent crime rate,43.0,1.237998e+06,3.024210e+08,409.362388,NaN,NaN,2014.0,0.0
7,AL,Alabama,1.0,0.0,2003-2005,Violent crime rate,43.0,1.817483e+04,4.221248e+06,430.555907,NaN,NaN,NaN,1000.0
8,AL,Alabama,1.0,0.0,2004-2006,Violent crime rate,43.0,1.767717e+04,4.042098e+06,437.326488,NaN,NaN,NaN,1000.0
9,AL,Alabama,1.0,0.0,2005-2007,Violent crime rate,43.0,1.745817e+04,3.979110e+06,438.745515,NaN,NaN,2010.0,1000.0

In [3]:
print("Dataset Overview:")
print("=" * 50)
print(f"Total samples: {len(df)}\n")
print(df.info())

Dataset Overview:
==================================================
Total samples: 303864

<class 'pandas.DataFrame'>
RangeIndex: 303864 entries, 0 to 303863
Data columns (total 14 columns):
 #   Column                           Non-Null Count   Dtype
---  ------                           --------------   -----
 0   State                            303858 non-null  str
 1   County                           303858 non-null  str
 2   State code                       303860 non-null  float64
 3   County code                      303860 non-null  float64
 4   Year span                        303390 non-null  str
 5   Measure name                     303390 non-null  str
 6   Measure id                       303390 non-null  float64
 7   Numerator                        214076 non-null  float64
 8   Denominator                      184779 non-null  float64
 9   Raw value                        289956 non-null  float64
 10  Confidence Interval Lower Bound  189412 non-null  float64
 11  Confidence Interval Upper Bound  189412 non-null  float64
 12  Data Release Year                150129 non-null  float64
 13  fipscode                         294283 non-null  float64
dtypes: float64(10), str(4)
memory usage: 32.5 MB
None

In [4]:
measure_names_df = pd.DataFrame({'Measure Names': df['Measure name'].unique()})
print("Unique Measure Names:")
display(measure_names_df)

Unique Measure Names:

                      Measure Names
0                Violent crime rate
1                      Unemployment
2               Children in poverty
3                               NaN
4                Diabetic screening
5             Mammography screening
6        Preventable hospital stays
7                         Uninsured
8   Sexually transmitted infections
9               Physical inactivity
10                    Adult obesity
11                  Premature Death
12    Daily fine particulate matter

In [5]:
year_span_df = pd.DataFrame({'Year spans': df['Year span'].unique()})
print("Unique Year Spans:")
display(year_span_df)

Unique Year Spans:

   Year spans
0   2003-2005
1   2004-2006
2   2005-2007
3   2006-2008
4   2007-2009
5   2008-2010
6   2009-2011
7        2002
8        2003
9        2004
10       2005
11       2006
12       2007
13       2008
14       2009
15       2010
16       2011
17       2012
18          .
19        NaN
20  2006-2007
21  1997-1999
22  1998-2000
23  1999-2001
24  2000-2002
25  2001-2003
26  2002-2004

## Handling Missing Values

In [6]:
# Checking for missing values
missing_values = df.isnull().sum()
missing_percentage = (missing_values / len(df)) * 100
missing_df = pd.DataFrame({'Missing Values': missing_values, 
                           'Percentage (%)': missing_percentage})
missing_df = missing_df[missing_df['Missing Values'] > 0].sort_values('Percentage (%)', ascending=False)

print("Missing Values Analysis:")
display(missing_df)

Missing Values Analysis:

                                 Missing Values  Percentage (%)
Data Release Year                        153735       50.593358
Denominator                              119085       39.190230
Confidence Interval Upper Bound          114452       37.665535
Confidence Interval Lower Bound          114452       37.665535
Numerator                                 89788       29.548745
Raw value                                 13908        4.577048
fipscode                                   9581        3.153055
Year span                                   474        0.155991
Measure name                                474        0.155991
Measure id                                  474        0.155991
State                                         6        0.001975
County                                        6        0.001975
State code                                    4        0.001316
County code                                   4        0.001316

## Further Analysis on 'fipscode' Missing Values

In [7]:
df[df['fipscode'].isnull()]['State'].unique()
df[df['fipscode'].isnull()]['County'].unique()

<StringArray>
[     'United States',            'Alabama',     'Autauga County',
     'Baldwin County',     'Barbour County',        'Bibb County',
      'Blount County',     'Bullock County',      'Butler County',
     'Calhoun County',
 ...
      'Goshen County', 'Hot Springs County',     'Laramie County',
     'Natrona County',    'Niobrara County',    'Sublette County',
  'Sweetwater County',       'Uinta County',    'Washakie County',
      'Weston County']
Length: 1927, dtype: str

In [8]:
df[df['fipscode'].isnull()][['State', 'County', 'Measure name', 'Raw value']].head(20)

      State           County         Measure name  Raw value
57565    US    United States  Children in poverty      0.226
57578    AL          Alabama  Children in poverty      0.276
57591    AL   Autauga County  Children in poverty      0.185
57604    AL   Baldwin County  Children in poverty      0.205
57617    AL   Barbour County  Children in poverty      0.470
57630    AL      Bibb County  Children in poverty      0.272
57643    AL    Blount County  Children in poverty      0.231
57656    AL   Bullock County  Children in poverty      0.432
57669    AL    Butler County  Children in poverty      0.421
57682    AL   Calhoun County  Children in poverty      0.314
57695    AL  Chambers County  Children in poverty      0.347
57708    AL  Cherokee County  Children in poverty      0.299
57721    AL   Chilton County  Children in poverty      0.302
57734    AL   Choctaw County  Children in poverty      0.301
57747    AL    Clarke County  Children in poverty      0.318
57760    AL      Clay County  Children in poverty      0.300
57773    AL  Cleburne County  Children in poverty      0.260
57786    AL    Coffee County  Children in poverty      0.225
57799    AL   Colbert County  Children in poverty      0.253
57812    AL   Conecuh County  Children in poverty      0.463

In [9]:
df[df['fipscode'].isnull()]['County'].str.contains('County').value_counts()

County
True     9020
False     561
Name: count, dtype: int64

In [10]:
df[(df['fipscode'].isnull()) & (df['County'].str.contains('County'))][['State', 'County', 'Measure name']].head(20)

      State            County         Measure name
57591    AL    Autauga County  Children in poverty
57604    AL    Baldwin County  Children in poverty
57617    AL    Barbour County  Children in poverty
57630    AL       Bibb County  Children in poverty
57643    AL     Blount County  Children in poverty
57656    AL    Bullock County  Children in poverty
57669    AL     Butler County  Children in poverty
57682    AL    Calhoun County  Children in poverty
57695    AL   Chambers County  Children in poverty
57708    AL   Cherokee County  Children in poverty
57721    AL    Chilton County  Children in poverty
57734    AL    Choctaw County  Children in poverty
57747    AL     Clarke County  Children in poverty
57760    AL       Clay County  Children in poverty
57773    AL   Cleburne County  Children in poverty
57786    AL     Coffee County  Children in poverty
57799    AL    Colbert County  Children in poverty
57812    AL    Conecuh County  Children in poverty
57825    AL      Coosa County  Children in poverty
57838    AL  Covington County  Children in poverty

In [11]:
df[(df['fipscode'].isnull()) & (df['County'].str.contains('County'))]['Measure name'].value_counts()

Measure name
Uninsured              6013
Children in poverty    3007
Name: count, dtype: int64

### Summary: 

Rows where 'fipscode' is null will be dropped
9020 county rows for 'Uninsured' and 'Children in poverty'
measures are missing FIPS codes due to a data sourcing issue.
561 state/national aggregate rows will be dropped as out of scope.

In [13]:
df[df['State'].isnull()]

,State,County,State code,County code,Year span,Measure name,Measure id,Numerator,Denominator,Raw value,Confidence Interval Lower Bound,Confidence Interval Upper Bound,Data Release Year,fipscode
157161,NaN,NaN,2.0,105.0,2008,Uninsured,85.0,600.0,1980.0,0.303,0.25596,0.35004,NaN,2105.0
157228,NaN,NaN,2.0,230.0,2008,Uninsured,85.0,153.0,792.0,0.193,0.15576,0.23024,NaN,2230.0
272420,NaN,NaN,NaN,NaN,1997-1999,Premature Death,1.0,97.0,NaN,9197.000,6605.90000,12467.30000,NaN,51560.0
272421,NaN,NaN,NaN,NaN,1998-2000,Premature Death,1.0,88.0,NaN,8781.000,6217.10000,12047.60000,NaN,51560.0
272422,NaN,NaN,NaN,NaN,1999-2001,Premature Death,1.0,52.0,NaN,NaN,NaN,NaN,NaN,51560.0
272423,NaN,NaN,NaN,NaN,2000-2002,Premature Death,1.0,23.0,NaN,NaN,NaN,NaN,NaN,51560.0

In [12]:
# Check for duplicates
print("-" * 50)
print(f"Duplicate entries: {df.duplicated().sum()}")

--------------------------------------------------
Duplicate entries: 6793